name: Pull Requests
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['14', '16']
        os: [ubuntu-latest]

    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
    - uses: rwjblue/setup-volta@v1
    - name: Yarn Install
      run: yarn install
    - name: Running ESLint
      run: |
        yarn lint
    - name: Running tests
      run: |
        yarn test
